///|
pub extend Version with Eq::{equal, not_equal}

///|
pub extend Version with @debug.Debug::{to_repr}

///|
pub extend DecodeLimits with Eq::{equal, not_equal}

///|
pub extend DecodeLimits with @debug.Debug::{to_repr}

///|
pub extend IppError with @debug.Debug::{to_repr}

///|
pub extend Resolution with Eq::{equal, not_equal}

///|
pub extend Resolution with @debug.Debug::{to_repr}

///|
pub extend IppDateTime with Eq::{equal, not_equal}

///|
pub extend IppDateTime with @debug.Debug::{to_repr}

///|
pub extend IppValue with Eq::{equal, not_equal}

///|
pub extend IppValue with @debug.Debug::{to_repr}

///|
pub extend Attribute with Eq::{equal, not_equal}

///|
pub extend Attribute with @debug.Debug::{to_repr}

///|
pub extend Group with Eq::{equal, not_equal}

///|
pub extend Group with @debug.Debug::{to_repr}

///|
pub extend Message with Eq::{equal, not_equal}

///|
pub extend Message with @debug.Debug::{to_repr}
